feat(question-service)!: implement CRUD operations for questions
CS3219-AY2425S1/cs3219-ay2425s1-project-g05 pull request #29
Opened 2024-09-22 17:24 UTC by elaineshijie

Addresses #26 , #27, #28 

### Question Service

Created a new question service that performs CRUD and filter operations. Implemented validation with Joi but yet to add tests. Please set up your own .env file with DEV_PORT (8003) & DEV_URI. 

### Additional information
- Added endpoints:
- POST /question-service: Create a new question.
  - GET /question-service: Retrieve a list of questions
  - GET /question-service/:id: Retrieve a specific question by ID.
  - PUT /question-service/:id: Update an existing question.
  - DELETE /question-service/:id: Delete a question by ID.
  - GET /question-service/filter/:  Filter questions based on provided query parameters (category & difficulty).
  - GET /questions/random/:  Find a random question matching provided query parameters (category & difficulty).
- Questions can have the same title as long as they have different difficulty levels.
- Questions cannot have the same description at all.
- Soft delete
- Implemented CORS middleware to allow requests from specified origins (port number 8000, 8001, 8002, 8004 local host)

2024-09-24 14:17 UTC, pzl111 commented on question-service/middlewares/cors.js
> +// PORT 8001 - AUTH SERVICE
minor nit i think its user service not auth service

2024-09-24 14:19 UTC, pzl111 commented on question-service/router/router.js
> +router.post('/', validateQuestion, createQuestion);
is this route meant to be protected? (i.e. only accessible by admins)

2024-09-24 14:21 UTC, pzl111 commented on question-service/router/router.js
> +router.route("/id/:id").put(updateQuestionById);
should create, delete and update be accessible only to admins? (while get is anyone)

2024-09-24 14:22 UTC, pzl111 commented on question-service/middlewares/cors.js
> +// PORT 8001 - AUTH SERVICE
minor nit line 11 i think its user service not auth service

2024-09-24 14:45 UTC, pzl111 commented on question-service/index.js
> +app.use(bodyParser.json());
i think you might also need cookieParser middleware to parse cookies from HTTP requests

2024-09-24 14:46 UTC, pzl111 requested changes
Some minor comments

2024-09-26 05:06 UTC, georgetayqy approved these changes
LGTM!

The service is deployed onto AWS and is available at the following links:

API Gateway: https://n4qffw5pr5.execute-api.ap-southeast-1.amazonaws.com/v1/api/question-service
Application Load Balancer: Hidden to prevent authorised access
ECS: Hidden behind Application Load Balancer

2024-09-26 05:06 UTC, georgetayqy commented on question-service/index.js
> +});
Added a healthz path for health checks needed by AWS ALB.

2024-09-26 05:06 UTC, georgetayqy commented on question-service/Dockerfile
> +CMD ["node", "index.js"]
Added a Dockerfile to help dockerise the application.

2024-09-27 09:42 UTC, pzl111 approved these changes

2024-09-29 07:38 UTC, pzl111 commented on question-service/middlewares/cors.js
> +// PORT 8000 - FRONTEND
I think frontend side is port 5173 for dev

2024-09-29 07:51 UTC, merged