feat!: Add refresh tokens
CS3219-AY2425S1/cs3219-ay2425s1-project-g05 pull request #93
Opened 2024-10-31 01:59 UTC by pzl111

Addresses #88

### Description

Currently we only have accessTokens, which do not expire and poses a security vulnerability as whoever obtains the accessToken can access our services indefinitely.
We implement the access-refresh token workflow. (Refer to additional information below to see how it works).
- Access Tokens: Tokens issued during login and regeneration, short-lived tokens used gain accesss to other services
- Refresh Tokens: Tokens issued ONLY during login, long-lived tokens used to regenerate accessTokens.
Currently accessTokens are set with 1min expiration, and refreshTokens with 2min expiration for testing.

Also added endpoints to verify validity of accessToken, refreshToken, and regenerate accessToken.
Temporarily uses in-memory cache of whitelisted refreshTokens, which are checked during regeneration.

### Additional information
1. User logs in, user-service issues a new accessToken and refreshToken stored in cookies.
2. User access other services with accessTokens and is allowed while accessToken is still valid.
3. When accessToken expires, other services will deny access.
4. Frontend needs to call user-service to regenerate a new accessToken.
5. If refreshToken is still valid, user-service issues a newAccessToken.
- If refreshToken is invalid: either refreshToken expired, or was from a previously logged in user that has logged out. User needs to re-login again to get a new refreshToken.
6. User can now access other services again.

![image](https://github.com/user-attachments/assets/c17726bd-2d59-4e8f-b5bc-b20c39a947c1)

2024-11-02 04:11 UTC, georgetayqy requested changes
Good job on implementing the refresh token feature! There are some nits to resolve before we can merge this PR!

2024-11-02 04:11 UTC, georgetayqy commented on user-service/middlewares/redis.js
> +    url: 'redis://localhost:6379' // Adjust the URL if using Docker or a remote instance
Should we use an environment variable here to allow us to switch endpoints during deployment?

2024-11-10 08:11 UTC, georgetayqy approved these changes
LGTM

2024-11-13 03:32 UTC, HollaG commented
Merged in #371f5b82152b1c2659f7759320f28b23afff3382

2024-11-13 04:08 UTC, closed without merging